# Generated by Django 2.0.3 on 2018-03-18 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apirest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='cupo_juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('puntos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='grupo_juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('prize', models.TextField()),
                ('release_date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cli_grup', to='apirest.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='token_reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('burn_date', models.DateField()),
                ('id_cupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apirest.cupo_juego')),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_group', to='apirest.grupo_juego')),
            ],
        ),
        migrations.CreateModel(
            name='user_cli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_usercli', to='apirest.cliente')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_usercli', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cupo_juego',
            name='id_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupo_grupo', to='apirest.grupo_juego'),
        ),
        migrations.AddField(
            model_name='cupo_juego',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupo_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
