# Generated by Django 2.0.3 on 2018-03-19 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0002_auto_20180318_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo_juego',
            name='release_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
