# Generated by Django 2.0.3 on 2018-03-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0003_auto_20180318_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token_reg',
            name='burn_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
